import { NextResponse } from "next/server";

// Sample data: TechPro Solutions Pvt Ltd — mathematically consistent Indian SME
export const SAMPLE_EXTRACTED_DATA = {
  company_name: "TechPro Solutions Pvt Ltd",
  financial_year: "2024-25",
  previous_financial_year: "2023-24",
  balance_sheet: {
    fixed_assets: 350,
    capital_wip: 10,
    long_term_investments: 25,
    deferred_tax_asset: 15,
    long_term_loans_advances: 10,
    other_non_current_assets: 5,
    inventories: 280,
    trade_receivables: 330,
    cash_and_equivalents: 180,
    short_term_loans_advances: 25,
    gst_itc_receivable: 42,
    tds_advance_tax_receivable: 28,
    other_current_assets: 20,
    share_capital: 100,
    reserves_surplus: 300,
    money_received_share_warrants: 0,
    long_term_borrowings: 290,
    deferred_tax_liability: 22,
    long_term_provisions: 18,
    short_term_borrowings: 210,
    trade_payables: 145,
    gst_payable: 28,
    tds_payable: 12,
    pf_esi_payable: 8,
    advance_from_customers: 50,
    other_current_liabilities: 137,
  },
  profit_loss: {
    revenue_from_operations: 1240,
    other_income: 20,
    cogs: 800,
    employee_expenses: 186,
    finance_costs: 55,
    depreciation: 45,
    other_expenses: 58,
    tax_expense: 26,
  },
  cash_flow: {
    operating_cf: 142,
    investing_cf: -72,
    financing_cf: -88,
    capex: 65,
  },
  previous_year_balance_sheet: {
    fixed_assets: 338,
    capital_wip: 8,
    long_term_investments: 25,
    deferred_tax_asset: 16,
    long_term_loans_advances: 12,
    other_non_current_assets: 4,
    inventories: 260,
    trade_receivables: 290,
    cash_and_equivalents: 235,
    short_term_loans_advances: 20,
    gst_itc_receivable: 35,
    tds_advance_tax_receivable: 22,
    other_current_assets: 18,
    share_capital: 100,
    reserves_surplus: 240,
    money_received_share_warrants: 0,
    long_term_borrowings: 348,
    deferred_tax_liability: 20,
    long_term_provisions: 15,
    short_term_borrowings: 200,
    trade_payables: 130,
    gst_payable: 22,
    tds_payable: 10,
    pf_esi_payable: 0,
    advance_from_customers: 45,
    other_current_liabilities: 148,
  },
  previous_year_profit_loss: {
    revenue_from_operations: 1090,
    other_income: 18,
    cogs: 690,
    employee_expenses: 162,
    finance_costs: 60,
    depreciation: 42,
    other_expenses: 52,
    tax_expense: 25,
  },
  previous_year_cash_flow: {
    operating_cf: 118,
    investing_cf: -55,
    financing_cf: -70,
    capex: 50,
  },
  promoter_loans: 45,
  msme_payables: 38,
  annual_loan_repayment: 58,
  headcount: 142,
  data_confidence: "high",
  document_type: "annual_report",
  currency_detected: "INR_LAKHS",
  notes:
    "Sample data for TechPro Solutions Pvt Ltd — a representative Indian SME in the technology services sector. All figures in ₹ Lakhs.",
};